Add securedrop-workstation-dom0-config 1.0.0-rc1
freedomofpress/securedrop-yum-test pull request #58
Opened 2024-06-26 21:13 UTC by legoktm

Name of package: securedrop-workstation-dom0-config 1.0.0-rc1

Refs <https://github.com/freedomofpress/securedrop-workstation/issues/1103>.

### Test plan

- [ ] Able to reproduce build locally with exact same checksum
- [ ] Tag in securedrop-workstation repository is correct: https://github.com/freedomofpress/securedrop-workstation/releases/tag/1.0.0-rc1
- [ ] Build logs are included: https://github.com/freedomofpress/build-logs/commit/315a07dfc7c116d5b1fed7f5753beffe26e3b38d

2024-06-26 22:29 UTC, cfm requested changes
- [ ] Able to reproduce build locally with exact same checksum

I've twice gotten the same different hash:

```sh-session
user@sd:~/securedrop-workstation$ git log -1 --oneline
5493e75 (HEAD, tag: 1.0.0-rc1, origin/release/1.0.0) gpg: Signature made Wed 26 Jun 2024 01:03:30 PM PDT
gpg:                using RSA key B5690EEEBB952194
gpg: Can't check signature: No public key
Merge pull request #1102 from freedomofpress/rc1-bump
user@sd:~/securedrop-workstation$ git status
HEAD detached at 1.0.0-rc1
nothing to commit, working tree clean
user@sd:~/securedrop-workstation$ make build-rpm
[...]
Build complete! RPMs and their checksums are:

6f80df742d454df50310d5ba158021eb20fc37b07b44ecd2bfad4b63145deea6  rpm-build/RPMS/noarch/securedrop-workstation-dom0-config-1.0.0rc1-1.fc37.noarch.rpm
```

[Versus](https://github.com/freedomofpress/build-logs/commit/315a07dfc7c116d5b1fed7f5753beffe26e3b38d#diff-34688ee3c5e75a19f226c11525787bc28fc4b1a03905ba0a603d8c8f3151bf32R169):


```sh-session
Build complete! RPMs and their checksums are:

1f511079679879ae92c37906331227dd25a775868524e608826ab09d851e0914  rpm-build/RPMS/noarch/securedrop-workstation-dom0-config-1.0.0rc1-1.fc37.noarch.rpm
```

- [x] Tag in securedrop-workstation repository is correct: https://github.com/freedomofpress/securedrop-workstation/releases/tag/1.0.0-rc1
- [x] Build logs are included: https://github.com/freedomofpress/build-logs/commit/315a07dfc7c116d5b1fed7f5753beffe26e3b38d

2024-06-26 22:42 UTC, legoktm commented
Hmmm, could you diffoscope against my rpm? Or if you upload yours somewhere I can diffoscope them.

2024-06-26 22:59 UTC, cfm commented
Sorry, @legoktm; I should have just done that.  In <https://gist.github.com/cfm/2419597f9df96c972366163f50d3cf17> it looks like it's all mtimes.  I haven't investigated why, but I can once I'm done with freedomofpress/securedrop-workstation#1101 unless you beat me to it.

2024-06-26 23:45 UTC, legoktm commented
Thanks, I can reproduce the hash/timestamps changing when I do a fresh checkout of the repo. Somehow a mtime(?) timestamp is leaking into the build. I'm mostly out of time to look into it today so if you have time to look that would be nice and I'll pick it up in the morning.

2024-06-27 00:38 UTC, cfm commented
Well, the new (`+`) mtimes in <https://gist.github.com/cfm/2419597f9df96c972366163f50d3cf17> are correct per:
- https://github.com/freedomofpress/securedrop-workstation/blob/5493e755606303e58caece302ccad57aa2c5e0bd/rpm-build/SPECS/securedrop-workstation-dom0-config.spec#L10-L12
- https://github.com/freedomofpress/securedrop-workstation/blob/5493e755606303e58caece302ccad57aa2c5e0bd/rpm-build/SPECS/securedrop-workstation-dom0-config.spec#L176

So what's puzzling is why one build would and another wouldn't respect `source_date_epoch_from_changelog` → `clamp_mtime_to_source_date_epoch`.

2024-06-27 14:38 UTC, legoktm commented
That's true for most cases, but not all of them exactly, like:
```
│ │ --rw-r--r--   1        0        0    34520 2024-02-07 16:50:13.000000 ./usr/share/licenses/securedrop-workstation-dom0-config/LICENSE
│ │ +-rw-r--r--   1        0        0    34520 2024-04-24 22:02:05.000000 ./usr/share/licenses/securedrop-workstation-dom0-config/LICENSE
```

Locally I have:
```
$ eza -l LICENSE 
.rw-r--r--@ 35k user  7 Feb 12:50 LICENSE
```
which lines up, note the UTC offset.

2024-06-27 14:52 UTC, legoktm commented
I am not sure if all the necessary RPM changes landed in F37, https://fedoraproject.org/wiki/Changes/ReproducibleBuildsClampMtimes is marked as accepted for F38. 

I am going to try reverting https://github.com/freedomofpress/securedrop-workstation/commit/15d61fe52e3aa731ec0032294fa3e7f61b92d89a to see if it helps.

2024-06-27 16:19 UTC, legoktm commented
I didn't make progress on what I had suggested above (as in, it didn't help with reproducibility), so given that we've verified everything is reproducible except timestamps, in standup today we agreed to move forward with a non-reproducible rc1 to unblock QA but continue working on reproduciblity as a blocker for the eventual release (and probably next RC).

2024-06-27 16:54 UTC, cfm approved these changes
Thanks, @legoktm; that's a good compromise to unblock this release candidate.  Approving based on the timestamp-only diff from diffoscope in <https://github.com/freedomofpress/securedrop-yum-test/pull/58#issuecomment-2192757062>.

2024-06-27 16:54 UTC, merged